Practica_Pre_Profesional/Controllers/AsignaturaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Practica_Pre_Profesional.Models;

namespace Practica_Pre_Profesional.Controllers
{
    public class AsignaturaController : Controller
    {
        private readonly BdpracticaContext _context;

        public AsignaturaController(BdpracticaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> ListarAsignatura()
        {
            return View(await _context.TbAsignaturas.ToListAsync());
        }
        public async Task<IActionResult> CreateAsigna()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsigna(string descripcion, int estado)
        {
            var param = new SqlParameter[]
            {
                new SqlParameter()
                {
                    ParameterName = "@descripcion",
                    SqlDbType = System.Data.SqlDbType.VarChar,
                    Value = descripcion
                },
                new SqlParameter()
                {
                    ParameterName= "@estado",
                    SqlDbType = System.Data.SqlDbType.Int,
                    Value = estado
                },

            };
            var InsertAsigna = await _context.Database.ExecuteSqlRawAsync($"exec Insert_Asignatura @descripcion,@estado ", param);
            if(InsertAsigna == 1)
            {
                return RedirectToAction("ListarAsignatura");
            }
            else
            {
                return View();
            };
        }


        public async Task<IActionResult> EditarAsig(int? id)
        {
            if(id == null)
            {
                return View(await _context.TbAsignaturas.ToListAsync());
            }
            var editar = await _context.TbAsignaturas.FindAsync(id);
            return View (editar);
        }
        [HttpPost]
        public async Task<IActionResult> EditarAsig(int? id, string descripcion, int estado)
        {
            var param = new SqlParameter[]
            {
               new SqlParameter()
               {
                   ParameterName="@Id",
                   SqlDbType = System.Data.SqlDbType.Int,
                   Value = id
               },
               new SqlParameter()
               {
                   ParameterName = "@descripcion",
                   SqlDbType = System.Data.SqlDbType.VarChar,
                   Value = descripcion
               },
               new SqlParameter()
               {
                   ParameterName = "@estado",
                   SqlDbType = System.Data.SqlDbType.Int,
                   Value = estado
                }
            };
            var EditarAsingna =await _context.Database.ExecuteSqlRawAsync($"exec Update_Asignatura @Id, @descripcion, @estado ", param);
            if (EditarAsingna == 1)
            {
                return RedirectToAction("ListarAsignatura");
            }
            else
            {
                return View();
            };
           
        }
            
        
        //public async Task<IActionResult> DeleteAsig(int id)
        //{
        //    var param = new SqlParameter[]
        //    {
        //        new SqlParameter()
        //        {
        //            ParameterName ="@Id",

        //            SqlDbType = System.Data.SqlDbType.Int,
        //            Value = id
        //        },

        //    };
        //    var eliminar = await _context.Database.ExecuteSqlRawAsync($"exec Delete_Asignatura @Id", param);
        //    return RedirectToAction("ListarAsignatura");
        //}
    }
}

Practica_Pre_Profesional/Controllers/LibroController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Practica_Pre_Profesional.Models;
using System.Reflection.Metadata;

namespace Practica_Pre_Profesional.Controllers
{
    public class LibroController : Controller
    {
        private readonly BdpracticaContext _context;

        public LibroController(BdpracticaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> ListarLibros()
        {
            var asingnatura = _context.TbLibros.Include(R => R.IdAsingNavigation);
         
            return View(await asingnatura.ToListAsync());
        }

        public async Task<IActionResult> FiltrarLibro(string Descripcion)
        {

            if (Descripcion == null)
            {
                var asingnatura = _context.TbLibros.Include(R => R.IdAsingNavigation);

                return View(await asingnatura.ToListAsync());
            }
            var movie = await _context.TbLibros.FirstOrDefaultAsync(m => m.Descripcion == Descripcion);

            if(movie == null)
            {
                var asingnatura = _context.TbLibros.Include(R => R.IdAsingNavigation);

                return View(await asingnatura.ToListAsync());
            }
            var movieList = new List<TbLibro> { movie };
            return View(movieList);

        }

        public IActionResult CreateLibro()
        {
            ViewData["asignatura"] = new SelectList(_context.TbAsignaturas, "IdAsig", "Descripcion");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateLibro (string Descripcion, int IdAsing, int stock)
        {
            var param = new SqlParameter[]
            {
                new SqlParameter()
                {
                    ParameterName= "@descripcion",
                    SqlDbType= System.Data.SqlDbType.VarChar,
                    Value=Descripcion
                },
                new SqlParameter()
                {
                    ParameterName = "@Id_asing",
                    SqlDbType = System.Data.SqlDbType.Int,
                    Value = IdAsing
                },
                new SqlParameter()
                {
                    ParameterName="@stock",
                    SqlDbType = System.Data.SqlDbType.Int,
                    Value = stock
                }
            };
            var InsertLibro = await _context.Database.ExecuteSqlRawAsync($"exec Insert_Libro @descripcion,@Id_asing,@stock", param);
            if(InsertLibro == 1)
            {
                return  RedirectToAction("ListarLibros");
            }
            else
            {
                return View();
            };
        }

        public async Task<IActionResult> EditarLibro(int id)
        {
            if(id == null)
            {
                var asingnatura = _context.TbLibros.Include(R => R.IdAsingNavigation);

                return View(await asingnatura.ToListAsync());
            }
            var editar = await _context.TbLibros.FindAsync(id);
            ViewData["asignatura"] = new SelectList(_context.TbAsignaturas, "IdAsig", "Descripcion");
            return View(editar);
        }

        [HttpPost]
        public async Task<IActionResult> EditarLibro(int id, string descripcion, int IdAsing, int stock)
        {
            var param = new SqlParameter[]
            {
                new SqlParameter()
                {
                    ParameterName = "@IdLibro",
                    SqlDbType = System.Data.SqlDbType.Int,
                    Value = id
                },
                new SqlParameter()
                {
                    ParameterName = "@descripcion",
                    SqlDbType = System.Data.SqlDbType.VarChar,
                    Value = descripcion
                },
                new SqlParameter()
                {
                    ParameterName = "@IdAsigna",
                    SqlDbType = System.Data.SqlDbType.Int,
                    Value =IdAsing
                },
                new SqlParameter()
                {
                    ParameterName = "@stock",
                    SqlDbType = System.Data.SqlDbType.Int,
                    Value = stock
                }
            };
            var EditarLibro = await _context.Database.ExecuteSqlRawAsync($"exec Update_Libro @IdLibro,@descripcion,@IdAsigna,@stock ", param);
            if (EditarLibro == 1)
            {
                return RedirectToAction("ListarLibros");
            }
            else
            {
                return View();
            };

        }

        public async Task<IActionResult> DeleteLibro(int id)
        {
            var param = new SqlParameter[]
            {
                new SqlParameter()
                {
                    ParameterName = "@Id",
                    SqlDbType = System.Data.SqlDbType.Int,
                    Value = id
                }
            };
            var eliminarLibro = await _context.Database.ExecuteSqlRawAsync($"exec delete_Libro @Id", param);
            return RedirectToAction("ListarLibros");

        }


    }
}

Practica_Pre_Profesional/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practica_Pre_Profesional</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practica_Pre_Profesional.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica_Pre_Profesional</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asignatura" asp-action="ListarAsignatura">Listar Asingatura</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="ListarLibros">Listar Libro</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Practica_Pre_Profesional - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>